# Generated by Django 5.0.6 on 2024-05-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoinsta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
